### ISSUE TITLE
一直报这个错误

### ISSUE THREAD

**Issue by bournes** [liucongg/UnilmChatchitRobot#1]
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory unilm_model/ or `from_tf` set to False

**Comment by liucongg** [comment]
> OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory unilm_model/ or `from_tf` set to False

需要讲模型下载后，放到指定位置
