### ISSUE TITLE
如何考虑上下文

### ISSUE THREAD

**Issue by guijuzhejiang** [liucongg/UnilmChatchitRobot#2]
现在的生成式聊天模型都是用单轮对话训练的，有没有什么架构能考虑到上下文训练模型吗？

**Comment by liucongg** [comment]
> 现在的生成式聊天模型都是用单轮对话训练的，有没有什么架构能考虑到上下文训练模型吗？

unilm其实也是可以考虑上下文的，只不过我没有使用多轮对话的数据，可以将不同的token_type表示不同说话的人
